package org.iacopobaroncini.FsTamTam;

public enum DataType {

    DATA_TYPE_BOOLEAN,
    DATA_TYPE_INTEGER,
    DATA_TYPE_DOUBLE,
    DATA_TYPE_TEXT,
    DATA_TYPE_LLA,
    DATA_TYPE_PBH,
    DATA_TYPE_XYZ,
    DATA_TYPE_AI_WAYPOINT,
    DATA_TYPE_FACILITY_AIRPORT,
    DATA_TYPE_FACILITY_WAYPOINT,
    DATA_TYPE_FACILITY_NDB,
    DATA_TYPE_FACILITY_VOR,
    DATA_TYPE_FACILITY_TACAN

}
